version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb-admin
      MONGO_INITDB_ROOT_PASSWORD: umasenhanadasegura
      MONGO_INITDB_DATABASE: loja-suplementos-reports
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: