spring:
  profiles:
    active: mongo
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loja-suplementos
      username: mongodb-admin
      password: umasenhanadasegura
      authentication-database: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  thymeleaf:
    cache: false
server:
  servlet:
    session:
      tracking-modes: cookie
  error:
    path: /error
